// Auto-generated by scripts/generate-routes.mts — do not edit manually.
// Run `npm run routes` to regenerate after adding or removing pages.

export const appRoutes = [
  "/",
  "/hellotesting",
  "/hellotesting/go-home"
] as const;

export type AppRoute = (typeof appRoutes)[number];
