/**
 * Scans src/app/[lang]/ for page.tsx files and generates a typed route map
 * at src/lib/routes.ts. Run via `npm run routes`.
 *
 * The generated file exports:
 *   - appRoutes: readonly tuple of all valid app-relative paths
 *   - AppRoute: union type of those paths
 */

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, posix } from "node:path";

const APP_DIR = join(process.cwd(), "src", "app", "[lang]");
const OUTPUT = join(process.cwd(), "src", "lib", "routes.ts");

function findPages(dir: string): string[] {
  const routes: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      routes.push(...findPages(full));
    } else if (entry === "page.tsx" || entry === "page.ts") {
      const rel = relative(APP_DIR, dir);
      const route = rel
        ? "/" + rel.split("\\").join("/") // normalise Windows separators
        : "/";
      routes.push(route);
    }
  }
  return routes.sort();
}

const routes = findPages(APP_DIR);

const lines = [
  "// Auto-generated by scripts/generate-routes.mts — do not edit manually.",
  `// Run \`npm run routes\` to regenerate after adding or removing pages.`,
  "",
  `export const appRoutes = ${JSON.stringify(routes, null, 2)} as const;`,
  "",
  "export type AppRoute = (typeof appRoutes)[number];",
  "",
];

writeFileSync(OUTPUT, lines.join("\n"), "utf-8");

console.log(`Generated ${OUTPUT} with ${routes.length} route(s):`);
routes.forEach((r) => console.log(`  ${r}`));
